apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wave-frontends
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - secretName: wave-retail-demos-tls
    hosts:
    - store.retail.demos.wavefunctionlabs.com
    - erp.retail.demos.wavefunctionlabs.com
    - labs.retail.demos.wavefunctionlabs.com
    - sts.retail.demos.wavefunctionlabs.com
    - search-api.retail.demos.wavefunctionlabs.com
    - erp-api.retail.demos.wavefunctionlabs.com
    - labs-frontend.retail.demos.wavefunctionlabs.com
    - orchestrator.retail.demos.wavefunctionlabs.com
  rules:
  - host: store.retail.demos.wavefunctionlabs.com
    http:
      paths:
      - path: /sts
        pathType: Prefix
        backend:
          service:
            name: wave-sts
            port:
              number: 8801
      - path: /search
        pathType: Prefix
        backend:
          service:
            name: wavesearch-api
            port:
              number: 8803
      - path: /erp
        pathType: Prefix
        backend:
          service:
            name: wavestore-erp-api
            port:
              number: 8802
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wavestore-frontend
            port:
              number: 8804
  - host: erp.retail.demos.wavefunctionlabs.com
    http:
      paths:
      - path: /sts
        pathType: Prefix
        backend:
          service:
            name: wave-sts
            port:
              number: 8801
      - path: /erp
        pathType: Prefix
        backend:
          service:
            name: wavestore-erp-api
            port:
              number: 8802
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wavestore-erp-frontend
            port:
              number: 8805
  - host: labs.retail.demos.wavefunctionlabs.com
    http:
      paths:
      - path: /sts
        pathType: Prefix
        backend:
          service:
            name: wave-sts
            port:
              number: 8801
      - path: /search
        pathType: Prefix
        backend:
          service:
            name: wavesearch-api
            port:
              number: 8803
      - path: /erp
        pathType: Prefix
        backend:
          service:
            name: wavestore-erp-api
            port:
              number: 8802
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wavesearch-frontend
            port:
              number: 8806
  - host: sts.retail.demos.wavefunctionlabs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wave-sts
            port:
              number: 8801
  - host: search-api.retail.demos.wavefunctionlabs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wavesearch-api
            port:
              number: 8803
  - host: erp-api.retail.demos.wavefunctionlabs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wavestore-erp-api
            port:
              number: 8802
  - host: labs-frontend.retail.demos.wavefunctionlabs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wavesearch-frontend
            port:
              number: 8806
  - host: orchestrator.retail.demos.wavefunctionlabs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wavesearch-frontend
            port:
              number: 8806
