apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wave-frontends
spec:
  ingressClassName: nginx
  rules:
  - host: store.wave.local
    http:
      paths:
      - path: /sts
        pathType: Prefix
        backend:
          service:
            name: wave-sts
            port:
              number: 8801
      - path: /search
        pathType: Prefix
        backend:
          service:
            name: wavesearch-api
            port:
              number: 8803
      - path: /erp
        pathType: Prefix
        backend:
          service:
            name: wavestore-erp-api
            port:
              number: 8802
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wavestore-frontend
            port:
              number: 8804
  - host: erp.wave.local
    http:
      paths:
      - path: /sts
        pathType: Prefix
        backend:
          service:
            name: wave-sts
            port:
              number: 8801
      - path: /erp
        pathType: Prefix
        backend:
          service:
            name: wavestore-erp-api
            port:
              number: 8802
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wavestore-erp-frontend
            port:
              number: 8805
  - host: labs.wave.local
    http:
      paths:
      - path: /sts
        pathType: Prefix
        backend:
          service:
            name: wave-sts
            port:
              number: 8801
      - path: /search
        pathType: Prefix
        backend:
          service:
            name: wavesearch-api
            port:
              number: 8803
      - path: /erp
        pathType: Prefix
        backend:
          service:
            name: wavestore-erp-api
            port:
              number: 8802
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wavesearch-frontend
            port:
              number: 8806
  - host: sts.wave.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wave-sts
            port:
              number: 8801
  - host: search-api.wave.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wavesearch-api
            port:
              number: 8803
  - host: erp-api.wave.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wavestore-erp-api
            port:
              number: 8802
  - host: storefront.wave.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wavestore-frontend
            port:
              number: 8804
  - host: erp-frontend.wave.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wavestore-erp-frontend
            port:
              number: 8805
  - host: labs-frontend.wave.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wavesearch-frontend
            port:
              number: 8806
