apiVersion: v1
kind: Service
metadata:
  name: retail-v2-search
  namespace: retail-v2
spec:
  selector:
    app: retail-v2
    role: search
  ports:
    - name: http
      port: 80
      targetPort: 8080
