apiVersion: v1
kind: ServiceAccount
metadata:
  name: retail-v2
  namespace: retail-v2
  annotations:
    azure.workload.identity/use: "true"
    azure.workload.identity/client-id: "REPLACE_WITH_MANAGED_IDENTITY_CLIENT_ID"
