apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wave-dev

bases:
  - ../../base

replicas:
  - name: wave-sts
    count: 1
  - name: wavestore-erp-api
    count: 1
  - name: wavesearch-api
    count: 1
  - name: wavestore-frontend
    count: 1
  - name: wavestore-erp-frontend
    count: 1
  - name: wavesearch-frontend
    count: 1

images:
  - name: ghcr.io/willeastbury/wave-sts
    newName: tileforgeacr.azurecr.io/wave-sts
    newTag: dev
  - name: ghcr.io/willeastbury/wavestore-erp-api
    newName: tileforgeacr.azurecr.io/wavestore-erp-api
    newTag: dev
  - name: ghcr.io/willeastbury/wavesearch-labs-retail-search-api
    newName: tileforgeacr.azurecr.io/wavesearch-labs-retail-search-api
    newTag: dev
  - name: ghcr.io/willeastbury/wavestore-frontend
    newName: tileforgeacr.azurecr.io/wavestore-frontend
    newTag: dev
  - name: ghcr.io/willeastbury/wavestore-erp-frontend
    newName: tileforgeacr.azurecr.io/wavestore-erp-frontend
    newTag: dev
  - name: ghcr.io/willeastbury/wavesearch-labs-frontend
    newName: tileforgeacr.azurecr.io/wavesearch-labs-frontend
    newTag: dev
